# Generated by Django 5.2.6 on 2025-09-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/profile_pics/default.webp', upload_to='media/profile_pics/'),
        ),
    ]
